#ifndef OFFSETS_H_INCLUDED_
#define OFFSETS_H_INCLUDED_

bool Offset_Init(unsigned long version, unsigned long base);
unsigned char* Offset(int offset);

/*<! BEGIN Offset !>*/
#define PROFILE_GET_FLOAT 1
#define PROFILE_GET_INT 2
#define OBJECT_FROM_HASH 3
#define ABILITY_FROM_UNIT 4
#define SELECTION_PRIO_GET 5
#define SELECTION_SUBGROUP_SET 6
#define SELECTION_SYNC 7
#define UNIT_CREATED_CALLER_RETN 8
#define MISS_TEXT_TAG_DISPLAY 9
#define UI_TEXT_DISPLAY 10
#define UI_TOGGLE 11
#define MISSILE_SPEED_GET 12
#define OBJECT_NAME_GET 13
#define SOUND_PLAY 14
#define UNIT_ARRAY_GET 15
#define STATE_GET 16
#define UNIT_FROM_HANDLE 17
#define ITEM_FROM_HANDLE 18
#define HANDLE_FROM_OBJECT 19
#define GAME_TIME_ELAPSED_GET 20
#define PACKET_SEND 21
#define TRIGGER_CALL_2 22
#define TRIGGER_CALL_1 23
#define TRIGGER_CALL_3 24
#define CPOREAL_FUNC1 25
#define CPOREAL_FUNC2 26
#define TEXTTAG_MANAGER_CONSTRUCT 27
#define TEXTTAG_MANAGER_CREATETEXT 28
#define TEXTTAG_MANAGER_SETTAGTEXT 29
#define TEXTTAG_MANAGER_SHOWTEXTTAG 30
#define Z_CONV 31
#define INPUT_KEY_DOWN 32
#define INPUT_KEY_UP 33
#define PLAYER_NAME_GET 34
#define MINIMAP_PING 35
#define WAR3_UNITTIP_GET 36
#define UNITTIP_CONSTRUCT 37
#define UNITTIP_DESTRUCT 38
#define LAYOUTFRAME_SETABSPOS 39
#define LAYOUTFRAME_GETRELPOINT 40
#define LAYOUTFRAME_SETRELPOS 41
#define LAYOUTFRAME_SETRELFRAME 42
#define LAYOUTFRAME_SETHEIGHT 43
#define LAYOUTFRAME_SETWIDTH 44
#define LAYOUTFRAME_UPDATEPOSITION 45
#define SIMPLEREGION_SETPARENT 46
#define SIMPLEREGION_SETCOLOR 47
#define SIMPLEFONTSTRING_CONSTRUCT 48
#define SIMPLEFONTSTRING_SETTEXT 49
#define SIMPLEFONTSTRING_GETTEXTWIDTH 50
#define SIMPLEFONTSTRING_INITFONT 51
#define SIMPLEFONTSTRING_INITTEXT 52
#define SIMPLETEXTURE_CONSTRUCT 53
#define SIMPLETEXTURE_FILLBITMAP 54
#define SIMPLETEXTURE_FILLCOLOR 55
#define SIMPLEFRAME_CONSTRUCT 56
#define SIMPLEFRAME_INITTEXTURESETTINGS 57
#define SIMPLEFRAME_APPLYTEXTURESETTINGS 58
#define SIMPLEFRAME_SETPARENT 59
#define SIMPLEBUTTON_CONSTRUCT 60
#define SIMPLEBUTTON_SETSTATE 61
#define SIMPLEBUTTON_SETSTATETEXTURE 62
#define SIMPLESTATUSBAR_CONSTRUCT 63
#define SIMPLESTATUSBAR_SETVALUERANGE 64
#define TEXTFRAME_CONSTRUCT 65
#define TEXTFRAME_INITFONT 66
#define TEXTFRAME_SETFONT 67
#define TEXTFRAME_SETSHADOW 68
#define TEXTFRAME_SETCOLOR 69
#define TEXTFRAME_SETTEXT 70
#define SKIN_GETPATHBYNAME 71
#define RCSTRING_CONSTRUCT 72
#define RCSTRING_SETSTRING 73
#define STATBAR_CONSTRUCT 74
#define RC_ASSIGN 75
#define OBSERVER_CONSTRUCT 76
#define INPUTOBSERVER_GET 77
#define FRAMENAMEHASHTABLE_GETHASHNODE 78
#define ABILITYSPELL_UPDATEUI 79
#define PLAYER_TECHTREE_GET 80
#define AGILEDATA_HASHKEY_GET 81
#define AGILETYPEDATA_NODE_GET 82
#define ABILITYDEFDATA_GET 83
#define ABILITYUIDEF_GET 84
#define NATIVEFUNC_NODE_CREATE 85
#define NATIVEFUNC_NODE_GET 86
#define JASS_STRING_RV_TO_RCSTRING 87
#define UNITDATA_NODE_GET 88
#define ITEMDATA_NODE_GET 89
#define PROJECTILE_POSITION_GET 90
#define DATASTORECACHE1460_VTABLE 91
#define STATBAR_VTABLE 92
#define COMMANDBUTTON_VTABLE 93
#define HEROBARBUTTON_VTABLE 94
#define AGENTTIMER_VTABLE 95
#define GLOBAL_MAP_INFO 96
#define GLOBAL_UI 97
#define GLOBAL_GLUEMGR 98
#define GLOBAL_WARCRAFT_GAME 99
#define GLOBAL_CGXDEVICE 100
#define GLOBAL_SIMPLETOP 101
#define GLOBAL_UPDATE_STAGE_SIZE 102
#define GLOBAL_WAR3WNDPROC 103
#define GLOBAL_PRESELECTUIDATA 104
#define GLOBAL_OBJECT_UNDER_CURSOR 105
#define GLOBAL_FRAMENAMEHASHTABLE 106
#define GLOBAL_TLS_INDEX 107
#define GLOBAL_AGILE_DATA 108
#define GLOBAL_UNITDATAHASHTABLE 109
#define GLOBAL_ITEMDATAHASHTABLE 110
#define UNIT_FRAMEPOSITION_GET 111
#define PRESELECTUI_VTABLE 112
#define PRESELECTUI_INIT 113
#define READFUNCPROFILE 114
#define FUNCPROFILEOBJ 115
#define VISION_CHECK_CALLER_RETN 116
#define VISION_MAINMAP_FOG 117
#define VISION_MINIMAP_UNIT_CALLER_RETN 118
#define VISION_VISIBLESTATECHECK_CALL 119
#define VISION_CHECK_CALLER_RETN_2 120
#define VISION_SOME_STATE_CHECK 121
#define IG_UNIT 122
#define IG_ITEM 123
#define IG_TRIGGER 124
#define IG_ABILITYATTACK 125
#define IG_MISSILE 126
#define IG_MISSILESPLASH 127
#define IG_MISSILEBOUNCE 128
#define IG_MISSILELINE 129
#define IG_ARTILLERY 130
#define IG_ARTILLERYLINE 131
#define AH_NATIVEFUNC 132
#define SIMPLEFRAME_SETLEVEL 133

#define EDITBOX_CONSTRUCT 134

#define FOCUSED_FRAME 135

#define COMMANDBUTTON_CONSTRUCT 136
#define COMMANDBUTTON_SETSOMEFLOAT 137

#define WINDOW_X 138
#define WINDOW_Y 139


#define MOUSE_X 140
#define MOUSE_Y 141


/*<! END Offset !>*/

#endif